abs_levs:
- 0
- 10
- 20
- 30
- 40
- 50
- 60
- 70
- 80
- 90
- 100
auxiliary_data_dir: /g/data/p66/ars599/work_esmvaltool/auxiliary_data
conf_level: 0.95
diff_levs:
- -30
- -25
- -20
- -15
- -10
- -5
- 0
- 5
- 10
- 15
- 20
- 25
- 30
exit_on_ncl_warning: false
input_files:
- /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP56_simple_v3_20230303_223149/preproc/sm/sm/sm_info.ncl
log_level: debug
output_file_type: png
plot_diff: true
plot_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP56_simple_v3_20230303_223149/plots/sm/latlon
plot_type: latlon
realms:
- land
recipe: recipe_perfmetrics_CMIP56_simple_v3.yml
region: global
run_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP56_simple_v3_20230303_223149/run/sm/latlon
script: latlon
show_global_avg: true
t_test: true
themes:
- phys
time_avg: annualclim
version: 2.7.1
work_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP56_simple_v3_20230303_223149/work/sm/latlon
