auxiliary_data_dir: /g/data/p66/ars599/work_esmvaltool/auxiliary_data
calc_grading: true
exit_on_ncl_warning: false
input_files:
- /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP56_simple_v3_20230303_223149/preproc/tas/tas/tas_info.ncl
legend_outside: true
log_level: debug
metric:
- RMSD
normalization:
- centered_median
output_file_type: png
plot_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP56_simple_v3_20230303_223149/plots/tas/grading
plot_stddev: ref_model
plot_type: cycle_latlon
realms:
- atmos
recipe: recipe_perfmetrics_CMIP56_simple_v3.yml
region: global
run_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP56_simple_v3_20230303_223149/run/tas/grading
script: grading
styleset: CMIP5
themes:
- phys
time_avg: monthlyclim
version: 2.7.1
work_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP56_simple_v3_20230303_223149/work/tas/grading
