auxiliary_data_dir: /g/data/p66/ars599/work_esmvaltool/auxiliary_data
colormap: WhiteBlueGreenYellowRed
exit_on_ncl_warning: false
input_files:
- /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_ncl_20230301_215058/preproc/example/ta/ta_info.ncl
log_level: debug
ncdf: default
output_file_type: png
plot_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_ncl_20230301_215058/plots/example/test_ta
projection: Mollweide
realms:
- atmos
recipe: recipe_ncl.yml
run_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_ncl_20230301_215058/run/example/test_ta
script: test_ta
themes:
- phys
version: 2.7.1
work_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_ncl_20230301_215058/work/example/test_ta
