auxiliary_data_dir: /g/data/p66/ars599/work_esmvaltool/auxiliary_data
calc_grading: true
exit_on_ncl_warning: false
input_files:
- /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP5_simple_20230228_053237/preproc/ts/ts/ts_info.ncl
legend_outside: true
log_level: debug
metric:
- RMSD
normalization:
- centered_median
output_file_type: png
plot_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP5_simple_20230228_053237/plots/ts/grading
plot_stddev: ref_model
plot_type: cycle_latlon
realms:
- atmos
- ocean
recipe: recipe_perfmetrics_CMIP5_simple.yml
region: global
run_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP5_simple_20230228_053237/run/ts/grading
script: grading
styleset: CMIP5
themes:
- phys
time_avg: monthlyclim
version: 2.7.1
work_dir: /g/data/p66/ars599/work_esmvaltool/esmvaltool_output/recipe_perfmetrics_CMIP5_simple_20230228_053237/work/ts/grading
